spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/master}
    username: ${SPRING_DATASOURCE_USERNAME:master}
    password: ${SPRING_DATASOURCE_PASSWORD:master}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

app:
  replication:
    topic: db-replication-events

server:
  port: 8081
